### ISSUE TITLE
Breadcrumbs??

### ISSUE THREAD

**Issue by koprty** [ChristinaKo/SoftDev_FoodMe#21]
"recommendations": 'Check your Request Details. You may have incorrectly used some params, or the request was malformed.'

Why am I getting this issue when trying to search nutrition facts on Nutritionix?

**Comment by ChristinaKo** [comment]
hey Lise, I ran python recipes.py and I got a response for the bread crumbs ? Maybe it has to do with all the random things you are printing out.
