### ISSUE TITLE
2 koprty contributers

### ISSUE THREAD

**Issue by koprty** [ChristinaKo/SoftDev_FoodMe#23]
When I push at homer, I get the standard green icon with my koprty username and icon. 
But when I push at home on my computer, I get a dull github cat unclickable koprty icon.

WHY??????   (I like my green GitHub face!!)

Anyone have any ideas how to fix this IMPORTANT ISSUE???

**Comment by ChristinaKo** [comment]
I think it has to do with email confirmation?? I had this issue before.
